// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/applications/ibc_query/v1/event.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/ibc-go/v4/modules/core/02-client/types"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type EventQuerySubmitted struct {
	Id                 string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path               string        `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	LocalTimeoutHeight *types.Height `protobuf:"bytes,3,opt,name=local_timeout_height,json=localTimeoutHeight,proto3" json:"local_timeout_height,omitempty"`
	LocalTimeoutStamp  uint64        `protobuf:"varint,4,opt,name=local_timeout_stamp,json=localTimeoutStamp,proto3" json:"local_timeout_stamp,omitempty"`
	QueryHeight        uint64        `protobuf:"varint,5,opt,name=query_height,json=queryHeight,proto3" json:"query_height,omitempty"`
}

func (m *EventQuerySubmitted) Reset()         { *m = EventQuerySubmitted{} }
func (m *EventQuerySubmitted) String() string { return proto.CompactTextString(m) }
func (*EventQuerySubmitted) ProtoMessage()    {}
func (*EventQuerySubmitted) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ae7439c9b13df65, []int{0}
}
func (m *EventQuerySubmitted) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventQuerySubmitted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventQuerySubmitted.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventQuerySubmitted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventQuerySubmitted.Merge(m, src)
}
func (m *EventQuerySubmitted) XXX_Size() int {
	return m.Size()
}
func (m *EventQuerySubmitted) XXX_DiscardUnknown() {
	xxx_messageInfo_EventQuerySubmitted.DiscardUnknown(m)
}

var xxx_messageInfo_EventQuerySubmitted proto.InternalMessageInfo

func (m *EventQuerySubmitted) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EventQuerySubmitted) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *EventQuerySubmitted) GetLocalTimeoutHeight() *types.Height {
	if m != nil {
		return m.LocalTimeoutHeight
	}
	return nil
}

func (m *EventQuerySubmitted) GetLocalTimeoutStamp() uint64 {
	if m != nil {
		return m.LocalTimeoutStamp
	}
	return 0
}

func (m *EventQuerySubmitted) GetQueryHeight() uint64 {
	if m != nil {
		return m.QueryHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*EventQuerySubmitted)(nil), "ibc.applications.ibc_query.v1.EventQuerySubmitted")
}

func init() {
	proto.RegisterFile("ibc/applications/ibc_query/v1/event.proto", fileDescriptor_6ae7439c9b13df65)
}

var fileDescriptor_6ae7439c9b13df65 = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xb1, 0x4e, 0xf3, 0x30,
	0x14, 0x85, 0xeb, 0xfe, 0xfd, 0x91, 0x70, 0x11, 0x12, 0x2e, 0x43, 0x54, 0x89, 0x50, 0x98, 0xca,
	0x50, 0x5b, 0xa1, 0x6c, 0x6c, 0x48, 0x48, 0x0c, 0x2c, 0xb4, 0xb0, 0xb0, 0x54, 0x89, 0x63, 0x35,
	0x57, 0x4a, 0x6a, 0x53, 0xdf, 0x44, 0xea, 0x5b, 0xf0, 0x58, 0x8c, 0x1d, 0x11, 0x13, 0x6a, 0x5f,
	0x04, 0xd9, 0x06, 0x54, 0xb6, 0xab, 0x7b, 0xcf, 0x77, 0x4e, 0x72, 0x4c, 0x2f, 0x20, 0x93, 0x22,
	0x35, 0xa6, 0x04, 0x99, 0x22, 0xe8, 0x85, 0x15, 0x90, 0xc9, 0xd9, 0x4b, 0xad, 0x96, 0x2b, 0xd1,
	0x24, 0x42, 0x35, 0x6a, 0x81, 0xdc, 0x2c, 0x35, 0x6a, 0x76, 0x02, 0x99, 0xe4, 0xbb, 0x52, 0xfe,
	0x2b, 0xe5, 0x4d, 0xd2, 0x3f, 0x75, 0x4e, 0x52, 0x2f, 0x95, 0x90, 0x25, 0xa8, 0x05, 0x3a, 0x3c,
	0x4c, 0x81, 0x3f, 0xff, 0x20, 0xb4, 0x77, 0xeb, 0xfc, 0x1e, 0x1c, 0x32, 0xad, 0xb3, 0x0a, 0x10,
	0x55, 0xce, 0x0e, 0x69, 0x1b, 0xf2, 0x88, 0x0c, 0xc8, 0x70, 0x7f, 0xd2, 0x86, 0x9c, 0x31, 0xda,
	0x31, 0x29, 0x16, 0x51, 0xdb, 0x6f, 0xfc, 0xcc, 0xee, 0xe9, 0x71, 0xa9, 0x65, 0x5a, 0xce, 0x10,
	0x2a, 0xa5, 0x6b, 0x9c, 0x15, 0x0a, 0xe6, 0x05, 0x46, 0xff, 0x06, 0x64, 0xd8, 0xbd, 0xec, 0xbb,
	0x2f, 0xe1, 0x2e, 0x9b, 0x7f, 0x27, 0x36, 0x09, 0xbf, 0xf3, 0x8a, 0x09, 0xf3, 0xdc, 0x63, 0xc0,
	0xc2, 0x8e, 0x71, 0xda, 0xfb, 0xeb, 0x66, 0x31, 0xad, 0x4c, 0xd4, 0x19, 0x90, 0x61, 0x67, 0x72,
	0xb4, 0x0b, 0x4c, 0xdd, 0x81, 0x9d, 0xd1, 0x03, 0xff, 0x9b, 0x3f, 0xa9, 0xff, 0xbd, 0xb0, 0xeb,
	0x77, 0xc1, 0xf2, 0xe6, 0xe9, 0x6d, 0x13, 0x93, 0xf5, 0x26, 0x26, 0x9f, 0x9b, 0x98, 0xbc, 0x6e,
	0xe3, 0xd6, 0x7a, 0x1b, 0xb7, 0xde, 0xb7, 0x71, 0xeb, 0xf9, 0x7a, 0x0e, 0x58, 0xd4, 0x19, 0x97,
	0xba, 0x12, 0x52, 0xdb, 0x4a, 0xfb, 0x8a, 0x47, 0x73, 0x2d, 0x9a, 0x2b, 0x51, 0xe9, 0xbc, 0x2e,
	0x95, 0x75, 0x2f, 0x60, 0xc5, 0x38, 0x19, 0xb9, 0x4b, 0x28, 0x1f, 0x57, 0x46, 0xd9, 0x6c, 0xcf,
	0x57, 0x37, 0xfe, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xa5, 0xbd, 0x15, 0x2a, 0xa7, 0x01, 0x00, 0x00,
}

func (m *EventQuerySubmitted) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventQuerySubmitted) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventQuerySubmitted) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.QueryHeight != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.QueryHeight))
		i--
		dAtA[i] = 0x28
	}
	if m.LocalTimeoutStamp != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.LocalTimeoutStamp))
		i--
		dAtA[i] = 0x20
	}
	if m.LocalTimeoutHeight != nil {
		{
			size, err := m.LocalTimeoutHeight.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Path) > 0 {
		i -= len(m.Path)
		copy(dAtA[i:], m.Path)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Path)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvent(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvent(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventQuerySubmitted) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.Path)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.LocalTimeoutHeight != nil {
		l = m.LocalTimeoutHeight.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.LocalTimeoutStamp != 0 {
		n += 1 + sovEvent(uint64(m.LocalTimeoutStamp))
	}
	if m.QueryHeight != 0 {
		n += 1 + sovEvent(uint64(m.QueryHeight))
	}
	return n
}

func sovEvent(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvent(x uint64) (n int) {
	return sovEvent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventQuerySubmitted) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventQuerySubmitted: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventQuerySubmitted: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Path", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Path = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LocalTimeoutHeight", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LocalTimeoutHeight == nil {
				m.LocalTimeoutHeight = &types.Height{}
			}
			if err := m.LocalTimeoutHeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LocalTimeoutStamp", wireType)
			}
			m.LocalTimeoutStamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LocalTimeoutStamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field QueryHeight", wireType)
			}
			m.QueryHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.QueryHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvent
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvent
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvent
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvent        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvent          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvent = fmt.Errorf("proto: unexpected end of group")
)
