// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/applications/ibc_query/v1/packet.proto

package types

import (
	fmt "fmt"
	_go "github.com/confio/ics23/go"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// IBCQueryPacketData defines a struct for the packet payload
type IBCQueryPacketData struct {
	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path        string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	QueryHeight uint64 `protobuf:"varint,3,opt,name=query_height,json=queryHeight,proto3" json:"query_height,omitempty"`
	// TODO
	// Proof specifications used in verifying counterparty state
	ProofSpecs []*_go.ProofSpec `protobuf:"bytes,4,rep,name=proof_specs,json=proofSpecs,proto3" json:"proof_specs,omitempty"`
}

func (m *IBCQueryPacketData) Reset()         { *m = IBCQueryPacketData{} }
func (m *IBCQueryPacketData) String() string { return proto.CompactTextString(m) }
func (*IBCQueryPacketData) ProtoMessage()    {}
func (*IBCQueryPacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c3b95af207674c8, []int{0}
}
func (m *IBCQueryPacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IBCQueryPacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IBCQueryPacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IBCQueryPacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IBCQueryPacketData.Merge(m, src)
}
func (m *IBCQueryPacketData) XXX_Size() int {
	return m.Size()
}
func (m *IBCQueryPacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_IBCQueryPacketData.DiscardUnknown(m)
}

var xxx_messageInfo_IBCQueryPacketData proto.InternalMessageInfo

func (m *IBCQueryPacketData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *IBCQueryPacketData) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *IBCQueryPacketData) GetQueryHeight() uint64 {
	if m != nil {
		return m.QueryHeight
	}
	return 0
}

func (m *IBCQueryPacketData) GetProofSpecs() []*_go.ProofSpec {
	if m != nil {
		return m.ProofSpecs
	}
	return nil
}

func init() {
	proto.RegisterType((*IBCQueryPacketData)(nil), "ibc.applications.ibc_query.v1.IBCQueryPacketData")
}

func init() {
	proto.RegisterFile("ibc/applications/ibc_query/v1/packet.proto", fileDescriptor_0c3b95af207674c8)
}

var fileDescriptor_0c3b95af207674c8 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x31, 0x4b, 0xc4, 0x30,
	0x1c, 0xc5, 0x2f, 0x77, 0x45, 0x30, 0x3d, 0x44, 0x32, 0x15, 0xc1, 0x50, 0x9d, 0x8a, 0x70, 0x09,
	0xbd, 0xba, 0xb9, 0x9d, 0x0e, 0xba, 0x9d, 0x15, 0x17, 0x97, 0x92, 0xa6, 0xb1, 0x0d, 0x5e, 0x4d,
	0x6c, 0xd2, 0xc2, 0x7d, 0x09, 0xf1, 0x63, 0x39, 0xde, 0xe8, 0x28, 0xed, 0x17, 0x91, 0xe6, 0x50,
	0xdc, 0x1e, 0xef, 0x3d, 0xde, 0x9f, 0xff, 0x0f, 0x5e, 0xc8, 0x9c, 0x53, 0xa6, 0xf5, 0x46, 0x72,
	0x66, 0xa5, 0x7a, 0x35, 0x54, 0xe6, 0x3c, 0x7b, 0x6b, 0x45, 0xb3, 0xa5, 0x5d, 0x4c, 0x35, 0xe3,
	0x2f, 0xc2, 0x12, 0xdd, 0x28, 0xab, 0xd0, 0xa9, 0xcc, 0x39, 0xf9, 0xdf, 0x25, 0x7f, 0x5d, 0xd2,
	0xc5, 0x27, 0x73, 0xdd, 0x28, 0xf5, 0x6c, 0xf6, 0xe5, 0xf3, 0x77, 0x00, 0xd1, 0xdd, 0xea, 0xfa,
	0x7e, 0x4c, 0xd7, 0x6e, 0xe5, 0x86, 0x59, 0x86, 0x8e, 0xe0, 0x54, 0x16, 0x01, 0x08, 0x41, 0x74,
	0x98, 0x4e, 0x65, 0x81, 0x10, 0xf4, 0x34, 0xb3, 0x55, 0x30, 0x75, 0x8e, 0xd3, 0xe8, 0x0c, 0xce,
	0xdd, 0x68, 0x56, 0x09, 0x59, 0x56, 0x36, 0x98, 0x85, 0x20, 0xf2, 0x52, 0xdf, 0x79, 0xb7, 0xce,
	0x42, 0x31, 0xf4, 0xdd, 0xb5, 0xcc, 0x68, 0xc1, 0x4d, 0xe0, 0x85, 0xb3, 0xc8, 0x5f, 0x1e, 0x13,
	0xc9, 0xcd, 0x32, 0x21, 0xeb, 0x31, 0x79, 0xd0, 0x82, 0xa7, 0x50, 0xff, 0x4a, 0xb3, 0x7a, 0xfc,
	0xec, 0x31, 0xd8, 0xf5, 0x18, 0x7c, 0xf7, 0x18, 0x7c, 0x0c, 0x78, 0xb2, 0x1b, 0xf0, 0xe4, 0x6b,
	0xc0, 0x93, 0xa7, 0xab, 0x52, 0xda, 0xaa, 0xcd, 0x09, 0x57, 0x35, 0xe5, 0xca, 0xd4, 0xca, 0x41,
	0x58, 0x94, 0x8a, 0x76, 0x97, 0xb4, 0x56, 0x45, 0xbb, 0x11, 0x66, 0x64, 0x64, 0x68, 0x12, 0x2f,
	0xc6, 0x64, 0x8f, 0xc7, 0x6e, 0xb5, 0x30, 0xf9, 0x81, 0x7b, 0x37, 0xf9, 0x09, 0x00, 0x00, 0xff,
	0xff, 0x89, 0x0a, 0x68, 0x8f, 0x49, 0x01, 0x00, 0x00,
}

func (m *IBCQueryPacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IBCQueryPacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IBCQueryPacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ProofSpecs) > 0 {
		for iNdEx := len(m.ProofSpecs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ProofSpecs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPacket(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.QueryHeight != 0 {
		i = encodeVarintPacket(dAtA, i, uint64(m.QueryHeight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Path) > 0 {
		i -= len(m.Path)
		copy(dAtA[i:], m.Path)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.Path)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPacket(dAtA []byte, offset int, v uint64) int {
	offset -= sovPacket(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *IBCQueryPacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.Path)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	if m.QueryHeight != 0 {
		n += 1 + sovPacket(uint64(m.QueryHeight))
	}
	if len(m.ProofSpecs) > 0 {
		for _, e := range m.ProofSpecs {
			l = e.Size()
			n += 1 + l + sovPacket(uint64(l))
		}
	}
	return n
}

func sovPacket(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPacket(x uint64) (n int) {
	return sovPacket(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *IBCQueryPacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IBCQueryPacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IBCQueryPacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Path", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Path = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field QueryHeight", wireType)
			}
			m.QueryHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.QueryHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProofSpecs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProofSpecs = append(m.ProofSpecs, &_go.ProofSpec{})
			if err := m.ProofSpecs[len(m.ProofSpecs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPacket(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPacket
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPacket
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPacket
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPacket        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPacket          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPacket = fmt.Errorf("proto: unexpected end of group")
)
